name: jupyter-python-data-bootcamp
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.9.6
  - numpy
  - pandas
  - matplotlib
  - jupyterlab=2
  - bs4
  - seaborn
  - plotly
  - urllib3
  - csvkit
