name: jupyter-python-data-bootcamp
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - python==3.9.6
  - numpy
  - pandas
  - matplotlib
  - jupyterlab=3.1.1
  - bs4
  - seaborn
  - plotly
  - urllib3
  - csvkit
