
name: jupyter-python-data-bootcamp
channels:
  - conda-forge
  - travis
  - anaconda
  - defaults
dependencies:
  - python=3.9.6
  - numpy
  - pandas
  - matplotlib
  - jupyterlab=3.1.1
  - bs4
  - seaborn
  - plotly
  - urllib3
  - csvkit
  - datashader 
  - functools 
  - requests 
  - fastparquet
